### ISSUE TITLE
Running example.report.php, I receive a 4xx error

### ISSUE THREAD

**Issue by lulibo** [erebusnz/gapi-google-analytics-php-interface#137] opened 2015-10-13 11:08 UTC
Hello,
I followed all steps, but when I run the page with example.report.php content the page is blank and on developer console I see that I'm receiving a 4xx error.

Is it something I need to check?

Thank you

**Comment by sankalpsans** [comment] 2015-10-13 19:26
Check your error logs. Usual path is:
Apache: `/var/log/apache2/error.log`,
Nginx `/var/log/nginx/error/log`

**Comment by erebusnz** [comment] 2015-11-13 13:21
4XX are generally errors associated with permissions (e.g. 403), and can be caused by Google Analytics permissions not correctly assigned to your XXXXXXXX@developer.gserviceaccount.com email for example.

As @sankalpsans suggested, you will have to check your logs or run your code with PHP error reporting / show errors enabled.

**Closed by erebusnz** 2015-11-13 13:21 UTC
